### ISSUE TITLE
Installing via pip does not install dependencies

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject/python-icat#88]
I've tried installing python-icat using pip and it doesn't install the dependencies. I'm not sure if this is intended but, from my own use of pip, I expected that it would. I tested this with an old environment (python 3.6.9, pip 9.0.1) and a new environment (python 3.9.6, pip 21.2.4) and had the same result.

In the [setup.py](https://github.com/icatproject/python-icat/blob/develop/setup.py#L157), I see:
```Python
setup(
    ...,
    requires = ["suds"],
    ...,
)
```

I'm not too experienced with setuptools, but the [latest documentation](https://setuptools.readthedocs.io/en/latest/references/keywords.html) states:
> Warning
> `requires` is superseded by `install_requires` and should not be used anymore.

Again, from my limited understanding, could the `requires = ...` line above be replaced with something like this:
```Python
setup(
    ...,
    python_requires=[">=3.4"],
    install_requires = ["suds-jurko"],
    extras_require = {
        "yaml":    ["PyYAML"],
        "xml":     ["lxml"],
        "scripts": ["requests"],
        "all":     ["PyYAML", "lxml", "requests"],
    }
    ...,
)
```

I suppose you may need to upgrade your setuptools for this to work.

**Comment by RKrahl** [comment]
It is intended. The problem is that I don't want to dictate in the setup script which suds version to use. You may either use `suds-jurko` or `suds-community`. (Actually, there are many more suds clones around, most of them abandoned, but these two are tested to work.) But you can't have them both installed at the same time.

In most cases, I would recommend `suds-community`, because it is actively maintained at the moment. But it doesn't work with ICAT server older than 4.9.0, see #72. So if your installation is supposed to be able to talk to such older ICAT servers, you'll need to use `suds-jurko` instead. (Note that python-icat does support ICAT down to 4.4.0.)

The Python package dependency mechanism doesn not seem to have a way to express something like "require any package implementing suds".  So, if I'd follow your advice, I'd force anybody to use `suds-jurko` and python-icat could not be used with `suds-community`.

(As a side remark: `python_requires`, `install_requires`, and `extras_require` is from `setuptools`. python-icat still uses `distutils` instead. I'll probably need to change this before Python 3.12, though.)

**Comment by stuartpullinger** [comment]
That's a shame. Thanks for the answer. I guess this is one to consider in the future.

**Comment by RKrahl** [comment]
I found a way to deal with that: as of #105, the setup script first checks if (any clone of) `suds` is installed and adds `suds` to the requirements only if that is not the case. As a result, if no `suds` clone is installed, `pip install python-icat` will install `suds` (which is now the new name of `suds-community`) along with `python-icat`. If you need `suds-jurko` in place of `suds-community`, you need to install it first, e.g. `pip install suds-jurko && pip install python-icat` will just work as expected.

I shortly reopened just to document that resolution and close per #105.
